# Generated by Django 5.2.5 on 2025-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childscreening',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childscreening',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
