# Generated by Django 5.2.5 on 2025-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_alter_childscreening_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childscreening',
            name='screening',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
