# Generated by Django 5.2.5 on 2025-08-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_data',
            field=models.BooleanField(default=False),
        ),
    ]
